services:
  - type: web
    name: rankkmate-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    root: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
